### ISSUE TITLE
possible to Mocking Dio retrofit by http-mock-adapter

### ISSUE THREAD

**Issue by tazik561** [lomsa-dev/http-mock-adapter#97] opened 2021-04-25 05:00 UTC
I am using Dio with retrofit plugin . I have called my web services like this: 
```
      var configs = await restClient.getMainConfig({
        "versionName": "1.0",
        "currentMenuVersion": "2.0",
        "test": "test"
      });
```

And This is restClient.getMainConfig content:

```
  @POST("/loadConfig")
  Future<MainModel> getMainConfig(@Body() request);
```
How can I test `restClient.getMainConfig`?

**Comment by GiorgiBeriashvili** [comment] 2021-06-07 06:55
Hello!

I tested and mocked multiple possible requests by using Retrofit just to be sure that everything is working, and I will share below what I think is the solution for your original example case:

```dart
import 'package:http_mock_adapter/http_mock_adapter.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:retrofit/retrofit.dart';
import 'package:dio/dio.dart';
import 'package:test/test.dart';

part 'example_test.g.dart';

@RestApi(baseUrl: 'https://example.com')
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;

  @POST('/loadConfig')
  Future<MainModel> getMainConfig(@Body() request);
}

@JsonSerializable()
class MainModel {
  String versionName;
  String currentMenuVersion;
  String test;

  MainModel({
    required this.versionName,
    required this.currentMenuVersion,
    required this.test,
  });

  factory MainModel.fromJson(Map<String, dynamic> json) => _$MainModelFromJson(
        json,
      );

  Map<String, dynamic> toJson() => _$MainModelToJson(this);
}

void main() {
  test('Mocks Retrofit client POST request as defined', () async {
    final dio = Dio();
    final dioAdapter = DioAdapter();
    final restClient = RestClient(dio);

    const configPayload = <String, dynamic>{
      'versionName': '1.0',
      'currentMenuVersion': '2.0',
      'test': 'test',
    };

    final mainModelResponse = MainModel(
      versionName: 'versionName Reply',
      currentMenuVersion: 'currentMenuVersion Reply',
      test: 'test Reply',
    );

    dio.httpClientAdapter = dioAdapter;

    dioAdapter.onPost(
      '/loadConfig',
      (request) => request.reply(200, mainModelResponse),
      data: configPayload,
    );

    final response = await restClient.getMainConfig(configPayload);

    print(response.toJson());

    expect(mainModelResponse.toJson(), response.toJson());
  });
}
```

Of course there is also generated `example_test.g.dart` which I won't include since it's not as relevant.

The result:

```
{versionName: versionName Reply, currentMenuVersion: currentMenuVersion Reply, test: test Reply}
✓ Mocks Retrofit client POST request as defined
```

The essential part is same as mocking `Dio`, there are generally following steps you can take:

1. Create `Dio`, `DioAdapter`, and `RestClient` instances and assign `dioAdapter` to `dio.httpClientAdapter`;
2. Leverage request handlers such as `onPost` to mock the behavior of request/reply processes;
3. Send requests from `restClient` and check if you got the expected predefined responses.

I think it is fairly straightforward. A good candidate to be added in documentation/examples for sure.

Thank you for bringing this issue to our attention! I hope I answered your question. Please let me know if there's anything else you are interested in or if the issue is resolved.

**Comment by GiorgiBeriashvili** [comment] 2021-07-23 16:32
I will close this as it is seemingly resolved. Feel free to re-open.

**Closed by GiorgiBeriashvili** 2021-07-23 16:32 UTC
Labels: medium priority
