### ISSUE TITLE
Incompatible with retrofit

### ISSUE THREAD

**Issue by elnurvl** [lomsa-dev/http-mock-adapter#92] opened 2021-04-07 13:53 UTC
## Description

I am using `retrofit` package. When I run tests, the following error keeps showing:
    Could not find mocked route matching request for /api/users/GET/{}/{page: 1}/{}
When I debug, I see the client sends perfectly normal requests, however, for some reason the adapter cannot resolve it properly.

## Steps to reproduce

1. Install `retrofit: ^2.0.0-beta1`
2. Setup an API client and some endpoints
3. Use `DioAdapter()` as the `httpAdapter ` of the Dio client.

## System details

The code is null-safe.

**Comment by elnurvl** [comment] 2021-04-08 14:34
I have debugged the code. It seems the adapter requires an exact match of the `data` and the `queryParameters`. The matcher does not see the `null`s and the empty maps equal, which requires users to pass empty maps for data and `queryParameters` in the `onGet` method.

It would also be nice to be able to mock the routes for every possible parameters and payload.

**Comment by wer-mathurin** [comment] 2021-04-15 02:09
The problem comes from
```
 void onGet(
    dynamic route,
    RequestHandlerCallback callback, {
    dynamic data ,
    Map<String, dynamic> queryParameters = const {},
    dynamic headers,
  }) 
```

if you just add the following and empty map when null it will work
```
 void onGet(
    dynamic route,
    RequestHandlerCallback callback, {
    dynamic data = const {},
    Map<String, dynamic> queryParameters = const {},
    dynamic headers,
  }) 
```

**Comment by GiorgiBeriashvili** [comment] 2021-06-07 07:52
> @LukaGiorgadze , I have debugged the code. It seems the adapter requires an exact match of the `data` and the `queryParameters`. The matcher does not see the `null`s and the empty maps equal, which requires users to pass empty maps for data and `queryParameters` in the `onGet` method.
> 
> It would also be nice to be able to mock the routes for every possible parameter, payload and header.

This is indeed the case. It is intended behavior, and I will try to justify it at the end of this comment, which hopefully will sound reasonable.

Regarding dynamic mocking which you implied at the end, the functionality already exists and is based on `Matchers` class. We do not yet have documentation regarding it but we will add it soon alongside examples. Here is the general usage case, though:

```dart
    // -- snip --
    dioAdapter.onPost(
      '/endpoint',
      (request) => request.reply(200, 'Success!'),
      data: {
        'id': Matchers.integer,
      },
    );
    // -- snip --
```

This will mock each request with same properties and **any** `int` value. There are other matchers available as well.



> The problem comes from the **mixin RequestRouted**
> 
> ```
>  void onGet(
>     dynamic route,
>     RequestHandlerCallback callback, {
>     dynamic data ,
>     Map<String, dynamic> queryParameters = const {},
>     dynamic headers,
>   }) 
> ```
> 
> if you just add the following and empty map when null it will work
> 
> ```
>  void onGet(
>     dynamic route,
>     RequestHandlerCallback callback, {
>     dynamic data = const {},
>     Map<String, dynamic> queryParameters = const {},
>     dynamic headers,
>   }) 
> ```

That is indeed a solution. Though, I respectfully disagree about the necessity of this solution.

I will offer the solution which I think is the most logical and optimal considering the circumstances.

## Solution

Retrofit package has a [@NoBody()](https://github.com/trevorwang/retrofit.dart/issues/326) annotation that assigns `null` to the `data` field, [which has been merged](https://github.com/trevorwang/retrofit.dart/pull/329) due to the same willingness that sometimes nothing needs to be sent as data in request.

Here is a usage scenario of `@NoBody()` annotation:

```dart
import 'package:http_mock_adapter/http_mock_adapter.dart';
import 'package:retrofit/retrofit.dart';
import 'package:dio/dio.dart';
import 'package:test/test.dart';

part 'example_test.g.dart';

@RestApi(baseUrl: 'https://example.com')
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;

  @POST('/endpoint')
  @NoBody()
  Future<Result> doNothing();
}

class Result {
  final String message;

  const Result({required this.message});

  factory Result.fromJson(Map<String, dynamic> json) => Result(
        message: json['message'] as String,
      );

  Map<String, dynamic> toJson() => {
        'message': message,
      };
}

void main() {
  test('Mocks Retrofit client POST request as defined', () async {
    final dio = Dio();
    final dioAdapter = DioAdapter();
    final restClient = RestClient(dio);

    const successResponse = Result(message: 'Success!');

    dio.httpClientAdapter = dioAdapter;

    dioAdapter.onPost(
      '/endpoint',
      (request) => request.reply(200, successResponse),
    );

    final response = await restClient.doNothing();

    print(successResponse.message);
    print(response.message);

    expect(successResponse.message, response.message);
  });
}
```

```
Success!
Success!
✓ Mocks Retrofit client POST request as defined
```

If you take a look at the generated `example_test.g.dart` file, you will find that data field is annulled: `final String? _data = null;` It would have been an empty `Map<String, dynamic>` if we hadn't used `@NoBody()`.

I believe that this is the most logical solution, since if we include an empty map by default in every request if an argument won't be provided, it won't really be helpful in other cases, since most users will probably expect the value to be `null` as nothing was provided. I think `Dio` by default has `data` field set to `null` as well, but I might be wrong.

Regardless, another solution which has already been posted is to simply include an empty map to `data` field if you don't plan to use `@NoBody()` annotation. The issue has arisen mostly due to Retrofit's intrinsic way of handling requests as I see, probably not by some bug or mistake on `http_mock_adapter`'s part.

What do you think, @elnurvl and @wer-mathurin ? Please let me know if `@NoBody()` annotation is indeed a fitting solution, or that if you disagree.

**Comment by wer-mathurin** [comment] 2021-06-07 13:22
@GiorgiBeriashvili  
@NoBody solution => LGTM

**Comment by GiorgiBeriashvili** [comment] 2021-06-15 20:28
I will close the issue as it is seemingly resolved.

Feel free to re-open if that's not the case!

**Closed by GiorgiBeriashvili** 2021-06-15 20:28 UTC
Labels: bug
