### ISSUE TITLE
Stream has already been listened to

### ISSUE THREAD

**Issue by areuokokok** [lomsa-dev/http-mock-adapter#76] opened 2021-02-09 06:43 UTC
## Description

Bad state: Stream has already been listened to.
How can I requset dio more than once?

**Comment by campfire5** [comment] 2021-02-09 12:46
Can you show us the full code of your test.

**Comment by GiorgiBeriashvili** [comment] 2021-02-16 19:45
This bug ought to be fixed as it happens during regular usage of the package quite often.

We will take a look. Thank you for the issue!

**Comment by kuhnroyal** [comment] 2021-02-18 23:34
Getting this as well.

```
  DioError [DioErrorType.DEFAULT]: Bad state: Stream has already been listened to.
  #0      _GeneratedStreamImpl._createSubscription (dart:async/stream_impl.dart:526:18)
  #1      _StreamImpl.listen (dart:async/stream_impl.dart:493:9)
  #2      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:53:16)
  #3      _BoundSinkStream.listen (dart:async/stream_transformers.dart:185:9)
  #4      DefaultTransformer.transformResponse (package:dio/src/transformer.dart:99:46)
  #5      DioMixin._dispatchRequest (package:dio/src/dio.dart:948:38)
  <asynchronous suspension>
  #6      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
  #7      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1121:22)
  #8      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
  #9      new Future.<anonymous closure> (dart:async/future.dart:175:37)
  #10     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
  #11     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
  #12     _rootRun (dart:async/zone.dart:1182:47)
  #13     _CustomZone.run (dart:async/zone.dart:1093:19)
  #14     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
  #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
  #16     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
  #17     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
  #18     _rootRun (dart:async/zone.dart:1190:13)
  #19     _CustomZone.run (dart:async/zone.dart:1093:19)
```

Adding `stream.asBroadcastStream(),` here solves it but I am not sure what the cause is:
https://github.com/lomsa-dev/http-mock-adapter/blob/main/lib/src/response.dart#L16

**Comment by kuhnroyal** [comment] 2021-02-18 23:55
Here is a failing example:

```dart
    test('foo', () async {
      final mock = DioAdapter();
      final dio = Dio()..httpClientAdapter = mock;
      mock.onPost('/bar', data: {"id": 5}).reply(200, null);

      final response = await dio.post<void>('/pet', data: {"id": 4});

      expect(response.statusCode, 200);
    });
```

**Comment by kuhnroyal** [comment] 2021-02-21 20:55
I think I found the source of this problem - the static `DioAdapter._dioAdapter` instance which is always returned when calling the factory `DioAdapter()`.

When you put multiple `group`s in a test file, this prevents error from being found at all. Failing tests are marked as success.
Multiple tests are run in parallel and responses are awaited but the all actually use and manipulate the same backing `History` instance. That is why sometimes the response has been closed already and other times there are false success message.

Getting rid of the static instance should fix a couple of these random untraceable errors.

**Comment by kuhnroyal** [comment] 2021-02-21 21:03
This would also partially solve #77 as every new `DioAdapter()` also has a clear history.

**Comment by kuhnroyal** [comment] 2021-02-22 21:04
What is the intention behind this static instance?

**Comment by idootop** [comment] 2021-02-23 05:55
> Getting this as well.
> 
> ```
>   DioError [DioErrorType.DEFAULT]: Bad state: Stream has already been listened to.
>   #0      _GeneratedStreamImpl._createSubscription (dart:async/stream_impl.dart:526:18)
>   #1      _StreamImpl.listen (dart:async/stream_impl.dart:493:9)
>   #2      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:53:16)
>   #3      _BoundSinkStream.listen (dart:async/stream_transformers.dart:185:9)
>   #4      DefaultTransformer.transformResponse (package:dio/src/transformer.dart:99:46)
>   #5      DioMixin._dispatchRequest (package:dio/src/dio.dart:948:38)
>   <asynchronous suspension>
>   #6      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
>   #7      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1121:22)
>   #8      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
>   #9      new Future.<anonymous closure> (dart:async/future.dart:175:37)
>   #10     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
>   #11     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
>   #12     _rootRun (dart:async/zone.dart:1182:47)
>   #13     _CustomZone.run (dart:async/zone.dart:1093:19)
>   #14     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
>   #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
>   #16     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
>   #17     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
>   #18     _rootRun (dart:async/zone.dart:1190:13)
>   #19     _CustomZone.run (dart:async/zone.dart:1093:19)
> ```
> 
> Adding `stream.asBroadcastStream(),` here solves it but I am not sure what the cause is:
> https://github.com/lomsa-dev/http-mock-adapter/blob/main/lib/src/response.dart#L16

But the response stream was done, when the request was sent the second time or more.
We expect to be able to respond it again.

**Comment by idootop** [comment] 2021-02-23 05:57
> What is the intention behind this static instance?

I'm also curious, but I think there must be a reason for doing so.

**Comment by kuhnroyal** [comment] 2021-02-23 11:53
@idootop The root cause is not the stream but the static history instance which returns/uses old responses which already have been closed. But those responses are the wrong ones anyways as the order has been messed up due to parallel tests.

The fix is not something with the stream but removing the static instance. Once I do that everything works.
My https://github.com/lomsa-dev/http-mock-adapter/issues/76#issuecomment-781705164 is outdated in that regard.

**Comment by kuhnroyal** [comment] 2021-02-23 12:10
@idootop Ok, I see now, you problem is separate and I have just reproduced that as well.

**Comment by kuhnroyal** [comment] 2021-02-23 15:11
I have created a PR for this which address all of these problems, please check it out.
A new builder syntax is needed to get rid of the static instances but I think it is worth it and also more in line with Dart builder/chaining style. It also fixes @idootop's problem.

**Comment by kuhnroyal** [comment] 2021-02-23 15:12
> > What is the intention behind this static instance?
> 
> I'm also curious, but I think there must be a reason for doing so.

As far as I can see, the only reason for them to exist is to allow creating request matcher chains. I have solved this with Dart builder/chaining (`..`) now.

**Comment by idootop** [comment] 2021-02-24 01:29
> I have created a PR for this which address all of these problems, please check it out.
> A new builder syntax is needed to get rid of the static instances but I think it is worth it and also more in line with Dart builder/chaining style. It also fixes @idootop's problem.

Nice work. Thanks bro.

**Comment by GiorgiBeriashvili** [comment] 2021-03-02 15:20
> Here is a failing example:
> 
> ```dart
>     test('foo', () async {
>       final mock = DioAdapter();
>       final dio = Dio()..httpClientAdapter = mock;
>       mock.onPost('/bar', data: {"id": 5}).reply(200, null);
> 
>       final response = await dio.post<void>('/pet', data: {"id": 4});
> 
>       expect(response.statusCode, 200);
>     });
> ```

Correct me if I am wrong, but should not this produce something akin an error due to both `route` and `data` mismatch?

I did test this example on v0.1.5 a while back and I did not get the `Stream has already been listened to...` error, but a signature mismatch error which makes a little more sense.

I also tested your suggested `stream.asBroadcastStream()` code and it did work, though it seems that you've made a PR with even more updates and benefits, and I will gladly take a look at that. Thank you for being helpful and sorry for responding late.

> What is the intention behind this static instance?

As far as I know, the static instance is used for `onGet(...)` and `reply()` and the similar method chaining, so that the same `DioAdapter` and/or `DioInterceptor` instances would be returned from the methods.

> As far as I can see, the only reason for them to exist is to allow creating request matcher chains. I have solved this with Dart builder/chaining (..) now.

Spot on! Nice thinking!

**Comment by kuhnroyal** [comment] 2021-03-02 15:27
> Correct me if I am wrong, but should not this produce something akin an error due to both route and data mismatch?
You are right, it should but it didn't. The thing is, if the `id` in the example matches then the test is successful. But if it doesn't then there is no test failure but the `Stream has already been listened to...` exception. Not completely sure why.

**Comment by GiorgiBeriashvili** [comment] 2021-03-06 21:32
#82 fixes the problems associated with this issue.

I will close the issue as I assume that @areuokokok and others will not experience the same problem again, but feel free to correct me if I am wrong.

**Closed by GiorgiBeriashvili** 2021-03-06 21:32 UTC
Labels: bug, help wanted, high priority, test
